name: Load Movies

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      days:
        description: "Days of changes"
        default: "2"
        required: true

jobs:
  load:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: npx ts-node scripts/load-new-movies.ts --db
