name: Load Movies

on:
  workflow_dispatch:
    inputs:
      days:
        description: "Days of changes"
        default: "0"
        required: true
  schedule:
    - cron: "50 19 * * *"

jobs:
  load:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: npx ts-node scripts/load-new-movies.ts --db --days ${{ github.event.inputs.days || '2' }}
